import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function sendAuditEmail(email, auditData) {
  const { totalMonthlySavings, totalAnnualSavings, results, summary } = auditData

  const toolRows = results.map(r => `
    <tr>
      <td style="padding:8px 0;border-bottom:1px solid #1f2937">
        <strong style="color:#fff">${r.toolName}</strong>
        <span style="color:#6b7280;font-size:12px;margin-left:8px">${r.currentPlan}</span>
      </td>
      <td style="padding:8px 0;border-bottom:1px solid #1f2937;text-align:right;color:#6b7280">
        $${r.currentSpend}/mo
      </td>
      <td style="padding:8px 0;border-bottom:1px solid #1f2937;text-align:right">
        ${r.savings > 0
          ? `<span style="color:#22c55e">save $${r.savings}/mo</span>`
          : `<span style="color:#6b7280">✓ optimal</span>`
        }
      </td>
    </tr>
  `).join('')

  const html = `
    <!DOCTYPE html>
    <html>
    <body style="background:#030712;color:#fff;font-family:system-ui,sans-serif;margin:0;padding:0">
      <div style="max-width:600px;margin:0 auto;padding:40px 24px">
        
        <div style="margin-bottom:32px">
          <span style="background:#052e16;color:#22c55e;border:1px solid #166534;padding:4px 12px;border-radius:999px;font-size:12px">
            SpendAudit by Credex
          </span>
        </div>

        <h1 style="font-size:28px;font-weight:700;margin:0 0 8px">
          Your AI Spend Audit
        </h1>

        ${totalMonthlySavings > 0 ? `
          <div style="background:#052e16;border:1px solid #166534;border-radius:12px;padding:24px;margin:24px 0;text-align:center">
            <p style="color:#22c55e;margin:0 0 8px;font-size:14px">💰 Savings opportunity found</p>
            <p style="font-size:36px;font-weight:700;margin:0 0 4px">$${totalMonthlySavings}/mo</p>
            <p style="color:#6b7280;margin:0">That's <strong style="color:#22c55e">$${totalAnnualSavings}/year</strong> you could save</p>
          </div>
        ` : `
          <div style="background:#111827;border:1px solid #1f2937;border-radius:12px;padding:24px;margin:24px 0;text-align:center">
            <p style="font-size:20px;font-weight:600;margin:0">✓ You're spending well</p>
          </div>
        `}

        ${summary ? `
          <div style="background:#111827;border:1px solid #1f2937;border-radius:12px;padding:20px;margin:24px 0">
            <p style="color:#22c55e;font-size:12px;margin:0 0 12px">AI Analysis</p>
            <p style="color:#d1d5db;line-height:1.6;margin:0">${summary}</p>
          </div>
        ` : ''}

        <h2 style="font-size:16px;font-weight:600;margin:24px 0 12px">Tool Breakdown</h2>
        <table style="width:100%;border-collapse:collapse">
          ${toolRows}
        </table>

        ${totalMonthlySavings > 500 ? `
          <div style="background:#052e16;border:1px solid #166534;border-radius:12px;padding:20px;margin:24px 0">
            <h3 style="margin:0 0 8px;font-size:16px">💡 Get even more savings with Credex</h3>
            <p style="color:#9ca3af;font-size:14px;margin:0 0 16px">
              Credex sells discounted AI credits — same tools, lower price.
            </p>
            <a href="https://credex.rocks" style="background:#22c55e;color:#000;padding:10px 20px;border-radius:8px;text-decoration:none;font-weight:600;font-size:14px">
              Book a consultation →
            </a>
          </div>
        ` : ''}

        <p style="color:#4b5563;font-size:12px;margin-top:40px;border-top:1px solid #1f2937;padding-top:20px">
          This audit was generated by SpendAudit, a free tool by 
          <a href="https://credex.rocks" style="color:#22c55e">Credex</a>. 
          We help startups save on AI infrastructure spend.
        </p>

      </div>
    </body>
    </html>
  `

  try {
    const { data, error } = await resend.emails.send({
      from: 'SpendAudit <onboarding@resend.dev>',
      to: email,
      subject: totalMonthlySavings > 0
        ? `Your AI Spend Audit — $${totalMonthlySavings}/mo savings found`
        : `Your AI Spend Audit — You're spending well`,
      html
    })

    if (error) throw new Error(error.message)
    return { success: true, id: data.id }

  } catch (error) {
    console.error('Email send failed:', error.message)
    return { success: false, error: error.message }
  }
}